

export enum PRODUCTS_ACTIONS {
    GET_PRODUCTS = "GET_PRODUCTS",
    ADD_PRODUCTS = "ADD_PRODUCTS",
    DELETE_PRODUCTS = "DELETE_PRODUCTS",
    EDIT_PRODUCTS = "EDIT_PRODUCTS",

}
export enum FAVOURITE_PRODUCTS_ACTIONS {
    GET_FAVOURITE_PRODUCTS = "GET_FAVOURITE_PRODUCTS",
    ADD_FAVOURITE_PRODUCTS = "ADD_FAVOURITE_PRODUCTS",
    DELETE_FAVOURITE_PRODUCTS = "DELETE_FAVOURITE_PRODUCTS",
    EDIT_FAVOURITE_PRODUCTS = "EDIT_FAVOURITE_PRODUCTS",

}